apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prd-

resources:
  - ../../base

configMapGenerator:
  - name: tcc-config
    envs:
      - .env.prd

secretGenerator:
  - name: tcc-secrets
    envs:
      - secrets-prd.env

generatorOptions:
  disableNameSuffixHash: true
