apiVersion: v1
kind: Service
metadata:
  name: kafka-tcc
  namespace: tcc
  labels:
    app: kafka-tcc
spec:
  selector:
    app: kafka-tcc
  ports:
  - name: external
    port: 9092
    targetPort: 9092
  - name: internal
    port: 29092
    targetPort: 29092
