apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-spliter-worker
  labels:
    app: document-spliter-worker
    type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-spliter-worker
  template:
    metadata:
      labels:
        app: document-spliter-worker
        type: worker
    spec:
      containers:
      - name: document-spliter-worker
        image: leandrorodriguescarneiro/tcc_api_ingestao_dados:latest
        command: ["python", "-m", "app.kafka.start_consumer", "document_spliter"]
        envFrom:
        - configMapRef:
            name: tcc-config
        - secretRef:
            name: tcc-secrets
        volumeMounts:      
        - name: shared-tmp
          mountPath: /app/tmp
      volumes:             
      - name: shared-tmp
        persistentVolumeClaim:
          claimName: shared-tmp
