apiVersion: apps/v1
kind: Deployment
metadata:
  name: docx-splitter-worker
  labels:
    app: docx-splitter-worker
    type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docx-splitter-worker
  template:
    metadata:
      labels:
        app: docx-splitter-worker
        type: worker
    spec:
      containers:
      - name: docx-splitter-worker
        image: leandrorodriguescarneiro/tcc_api_ingestao_dados:latest
        command: ["python", "-m", "app.kafka.start_consumer", "docx_worker"]
        envFrom:
        - configMapRef:
            name: tcc-config
        - secretRef:
            name: tcc-secrets
        volumeMounts:         
        - name: shared-tmp
          mountPath: /app/tmp
      volumes:                
      - name: shared-tmp
        persistentVolumeClaim:
          claimName: shared-tmp
