apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-splitter-worker
  labels:
    app: pdf-splitter-worker
    type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-splitter-worker
  template:
    metadata:
      labels:
        app: pdf-splitter-worker
    spec:
      containers:
      - name: pdf-splitter-worker
        image: leandrorodriguescarneiro/tcc_api-ingestao-dados:latest
        command: ["python", "-m", "app.kafka.start_consumer", "pdf_worker"]
        envFrom:
        - configMapRef:
            name: tcc-config
        - secretRef:
            name: tcc-secrets
        volumeMounts:
          - name: shared-tmp
            mountPath: /app/tmp
      volumes:
      - name: shared-tmp
        persistentVolumeClaim:
          claimName: shared-tmp
