apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-chat
  labels:
    app: api-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-chat
  template:
    metadata:
      labels:
        app: api-chat
    spec:
      containers:
      - name: api-chat
        image: leandrorodriguescarneiro/tcc_api_chat:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: tcc-config
        - secretRef:
            name: tcc-secrets