apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-tcc
  labels:
    app: zookeeper-tcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-tcc
  template:
    metadata:
      labels:
        app: zookeeper-tcc
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.5.0
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_INIT_LIMIT
          value: "10"
        - name: ZOOKEEPER_SYNC_LIMIT
          value: "5"
        - name: ZOOKEEPER_SERVER_ID
          value: "1"
        - name: ZOOKEEPER_SERVERS
          value: "zookeeper-tcc:2888:3888"
        volumeMounts:
        - name: zookeeper-data
          mountPath: /var/lib/zookeeper
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "echo ruok > /dev/tcp/127.0.0.1/2181 || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: zookeeper-data
        emptyDir: {}
