apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: hml-

resources:
  - ../../base

configMapGenerator:
  - name: tcc-config
    envs:
      - .env.hml

secretGenerator:
  - name: tcc-secrets
    envs:
      - secrets-hml.env

generatorOptions:
  disableNameSuffixHash: true
