apiVersion: v1
kind: Service
metadata:
  name: api-ingestao-dados
  labels:
    app: api-ingestao-dados
spec:
  selector:
    app: api-ingestao-dados
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP