apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tcc

resources:
  - namespace.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml
  - zookeeper/deployment.yaml
  - zookeeper/service.yaml
  - kafka/deployment.yaml
  - kafka/service.yaml
  - workers/deployments-workers.yaml