apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tcc

resources:
  - namespace.yaml
  - volumes.yaml
  - postgres/
  - zookeeper/
  - kafka/
  - chromadb/
  - api-autenticacao/
  - api-ingestao-dados/
  - workers/
  - api-chat/
  - frontend

configMapGenerator:
  - name: tcc-config
    literals:
      - placeholder=dummy

secretGenerator:
  - name: tcc-secrets
    literals:
      - placeholder=dummy