apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tcc

resources:
  - ../../base

configMapGenerator:
  - name: tcc-config
    envs:
      - .env.dev
    behavior: replace

secretGenerator:
  - name: tcc-secrets
    envs:
      - secrets-dev.env
    behavior: replace

images:
  - name: leandrorodriguescarneiro/tcc_api-autenticacao
    newTag: latest
  - name: leandrorodriguescarneiro/tcc_api-ingestao-dados
    newTag: latest
  - name: leandrorodriguescarneiro/tcc_api-chat
    newTag: latest
