apiVersion: v1
kind: Service
metadata:
  name: api-autenticacao
  labels:
    app: api-autenticacao
spec:
  selector:
    app: api-autenticacao
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP